/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_tajo_worker_Task */

#ifndef _Included_org_apache_tajo_worker_Task
#define _Included_org_apache_tajo_worker_Task
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_tajo_worker_Task_FETCHER_PROGRESS
#define org_apache_tajo_worker_Task_FETCHER_PROGRESS 0.5f
/*
 * Class:     org_apache_tajo_worker_Task
 * Method:    runJsonPlan
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_tajo_worker_Task_runJsonPlan
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_tajo_worker_Task
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_tajo_worker_Task_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
